name: Deploy wallet preview to netlify at PR and pushes to it
on:
  pull_request:
    paths:
      - "packages/anoma-wallet/**"
      - "packages/anoma-lib/**"
      - "packages/seed-management/**"
      - ".github/workflows/**"

env:
  CI: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./packages/anoma-wallet
        run: yarn

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "v0.10.2"

      - name: build the site
        working-directory: ./packages/anoma-wallet
        run: yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: "./packages/anoma-wallet/build"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "deploy ${{ github.event.number }} at creating a PR"
          alias: pull-request-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN_WALLET_PREVIEW }}
          NETLIFY_SITE_ID: 2380782e-9b20-477a-bc27-b4e9d05e16f3

      - name: Slack Notification
        run: |
          curl --header "Content-Type: application/json" \
          --request POST \
          --data '{"message":"New deployment for a PR\nhttps://pull-request-${{ github.event.number }}--wallet-preview-heliax-dev.netlify.app\n \nthe PR\nhttps://github.com/heliaxdev/namada-interface/pull/${{ github.event.number }}"}' \
          ${{ secrets.SLACK_WEBHOOK_WALLET_PR }}
