name: Deploy wallet preview to netlify at PR and pushes to it
on:
  pull_request:
  # push:
  # pull_request:
  #   paths:
  #     - "packages/anoma-wallet/**"
  #     - "packages/anoma-lib/**"
  #     - "packages/seed-management/**"
  #     - ".github/workflows/**"

env:
  CI: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./packages/anoma-wallet
        run: yarn

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "v0.10.3"

      - name: build the site
        working-directory: ./packages/anoma-wallet
        run: yarn build
        env:
          REACT_APP_ALIAS: "Namada Mainnet"
          REACT_APP_CHAIN_ID: "anoma-masp-1.5.32ccad5356012a7"
          REACT_APP_LEDGER_URL: "https://d3brk13lbhxfdb.cloudfront.net/anoma-masp-1.5.32ccad5356012a7"
          REACT_APP_FAUCET: "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
          REACT_APP_CHAIN_A_ALIAS: "Namada Instance 1"
          REACT_APP_CHAIN_A_ID: "anoma-ibc-0.4.5b0d5e5569aa27fb"
          REACT_APP_CHAIN_A_URL: "https://d3brk13lbhxfdb.cloudfront.net/anoma-ibc-0.4.5b0d5e5569aa27fb"
          REACT_APP_CHAIN_A_FAUCET: "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
          REACT_APP_CHAIN_B_ALIAS: "Namada Instance 2"
          REACT_APP_CHAIN_B_ID: "anoma-ibc-0.5.b574a0d30d21f7ed"
          REACT_APP_CHAIN_B_URL: "https://d3brk13lbhxfdb.cloudfront.net/anoma-ibc-0.5.b574a0d30d21f7ed"
          REACT_APP_CHAIN_B_FAUCET: "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
          REACT_APP_CHAIN_B_CHANNEL: "channel-1"

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: "./packages/anoma-wallet/build"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "deploy ${{ github.event.number }} at creating a PR"
          alias: pull-request-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN_WALLET_PREVIEW }}
          NETLIFY_SITE_ID: 1f548c68-c620-4522-97e0-0d85c08366fb
          # namada.me
          # NETLIFY_SITE_ID: 2380782e-9b20-477a-bc27-b4e9d05e16f3

      - name: Slack Notification
        run: |
          curl --header "Content-Type: application/json" \
          --request POST \
          --data '{"message":"New deployment for a PR\nhttps://pull-request-${{ github.event.number }}--wallet-preview-heliax-dev.netlify.app\n \nthe PR\nhttps://github.com/anoma/namada-interface/pull/${{ github.event.number }}"}' \
          ${{ secrets.SLACK_WEBHOOK_WALLET_PR }}
