name: run e2e tests
on:
  push:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        working-directory: ./packages/anoma-wallet
        run: yarn wasm:build && yarn
      - name: Install Playwright Browsers
        working-directory: ./packages/anoma-wallet
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./packages/anoma-wallet
        run: yarn playwright test
      - uses: actions/upload-artifact@v2
        working-directory: ./packages/anoma-wallet
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
