name: run e2e tests
on:
  push:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/anoma-wallet
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      # - name: Install wasm-pack
      #   uses: jetli/wasm-pack-action@v0.3.0
      #   with:
      #     version: "v0.10.3"
      # - name: Install dependencies
      #   run: |
      #     echo "check location"
      #     pwd
      #     yarn wasm:build && yarn
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: PLAYWRIGHT_BASE_URL=https://pull-request-${{ github.event.number }}--wallet-preview-heliax-dev.netlify.app yarn playwright test
      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
